name: Deploy Firebase
on:
  push:
    branches: [ 'feature/firebase' ]
jobs:
  firebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Install eslint
      run: npm install -g eslint
    - name: Deploy firebase
      run: npm run firebase-deploy:${GITHUB_REF_NAME} -- --token ${{ secrets.FIREBASE_TOKEN }}
