name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn --package-lock=false @typescript-eslint/eslint-plugin @typescript-eslint/parser babel-eslint eslint eslint-plugin-cypress eslint-plugin-rxjs gulp-eslint
    - name: Run ESLint
      run: yarn lint
