name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.npm-cache-dir-path.outputs.dir }}

        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
